name: 'Quartus Compilation Flow'
description: 'A GitHub Action for Quartus RTL Synthesis'
inputs:
  project:
    description: 'Project File'
    required: true
  revision:
    description: 'Revision Name'
    required: false
    default: ""
  version:
    description: 'Version/Alias'
    required: false
    default: "17.1"
  project_folder:
    description: 'Project Folder'
    required: false
    default: "projects"
runs:
  using: 'composite'
  steps:
    - name: "Compilation Flow"
      shell: bash
      run: |
        revision_cmd=""
        if [ -n "${{ inputs.revision }}" ]; then
          revision_cmd=" -c ${{ inputs.revision }}"
        fi

        cmd="docker run --rm -v ${{ github.workspace }}:/build raetro/quartus:${{ inputs.version }} quartus_sh --flow compile ${{ inputs.project_folder }}/${{ inputs.project }}${revision_cmd}"
        echo "Running command: $cmd"
        eval $cmd